qodana:
   image:
      name: jetbrains/qodana-python-community:2023.3
      entrypoint: [""]
   variables:
      QODANA_TOKEN: $qodana_token
   script:
      - qodana
   artifacts:
      paths:
         - qodana